# Generated by Django 4.1.13 on 2024-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'Default'), ('project_manager', 'Project Manager'), ('product_manager', 'Product Manager'), ('frontend_engineer', 'Frontend Engineer'), ('backend_engineer', 'Backend Engineer'), ('designer', 'Designer'), ('qa_tester', 'QA Tester'), ('devops_engineer', 'DevOps Engineer')], default='Default', max_length=20),
        ),
    ]
