# Generated by Django 4.1.13 on 2024-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Default', 'Default'), ('Project Manager', 'Project Manager'), ('Product Manager', 'Product Manager'), ('Frontend Engineer', 'Frontend Engineer'), ('Backend Engineer', 'Backend Engineer'), ('UI Designer', 'UI Designer'), ('QA Tester', 'QA Tester'), ('DevOps Engineer', 'DevOps Engineer')], default='Default', max_length=20),
        ),
    ]
