# Generated by Django 4.1.13 on 2024-03-06 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_document_id_remove_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.UUIDField(default=uuid.UUID('c947e887-6935-4ccc-bb55-374a1a406caf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('09a4ebff-2499-4919-a218-c9caf6122f68'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('d56d1b7d-b34b-42f2-8933-ea558a6cdeea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
