# Generated by Django 4.1.13 on 2024-03-11 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_document_document_id_alter_document_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.UUIDField(default=uuid.UUID('28185b35-c81a-4fa6-b874-3c46051e192a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='method',
            field=models.CharField(blank=True, choices=[('Scrum', 'Scrum'), ('Prince2', 'PRINCE2'), ('Waterfall', 'Waterfall')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('0e23f22a-3e89-478f-a128-f3a6fd569ed2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('To Do', 'To do'), ('In Progress', 'In Progress'), ('done', 'Done')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('8c309f71-5ce2-4b5f-9842-36735324de90'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
