# Generated by Django 4.1.13 on 2024-03-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('business_case', 'Business Case'), ('benefits_management_approach', 'Benefits Management Approach'), ('change_control_approach', 'Change Control Approach'), ('daily_log', 'Daily Log')], max_length=50),
        ),
    ]
