# Generated by Django 4.1.13 on 2024-03-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('To Do', 'To do'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Under Review', 'Under Review'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
