# Generated by Django 4.1.13 on 2024-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Planning', 'Planning'), ('Review', 'Review'), ('Backend Devt', 'Backend Devt'), ('Feature Devt', 'Feature Devt'), ('UI Design', 'UI Design')], max_length=20, null=True),
        ),
    ]
