# Generated by Django 4.1.13 on 2024-03-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_commenter_alter_comment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timeStamp']},
        ),
    ]
